'use strict';
const $=s=>document.querySelector(s);
const cities=[['杭州',30.2741,120.1551],['北京',39.9042,116.4074],['上海',31.2304,121.4737],['成都',30.5728,104.0668],['大理',25.6065,100.2676],['三亚',18.2528,109.5119],['西安',34.3416,108.9398],['重庆',29.5630,106.5516],['广州',23.1291,113.2644],['深圳',22.5431,114.0579],['南京',32.0603,118.7969],['苏州',31.2989,120.5853],['厦门',24.4798,118.0894],['长沙',28.2282,112.9388],['武汉',30.5928,114.3055],['青岛',36.0671,120.3826],['济南',36.6512,117.1201],['天津',39.0842,117.2009],['郑州',34.7466,113.6254],['洛阳',34.6197,112.4540],['昆明',25.0389,102.7183],['丽江',26.8550,100.2278],['香格里拉',27.8297,99.7008],['西双版纳',22.0017,100.7979],['拉萨',29.6520,91.1721],['林芝',29.6489,94.3615],['乌鲁木齐',43.8256,87.6168],['喀什',39.4704,75.9898],['伊宁',43.9095,81.2779],['哈尔滨',45.8038,126.5350],['长春',43.8171,125.3235],['沈阳',41.8057,123.4315],['大连',38.9140,121.6147],['呼和浩特',40.8426,111.7492],['呼伦贝尔',49.2116,119.7657],['太原',37.8706,112.5489],['大同',40.0768,113.3001],['石家庄',38.0428,114.5149],['秦皇岛',39.9354,119.5996],['合肥',31.8206,117.2272],['黄山',29.7147,118.3376],['南昌',28.6820,115.8579],['景德镇',29.2687,117.1784],['婺源',29.2479,117.8618],['福州',26.0745,119.2965],['泉州',24.8741,118.6757],['宁波',29.8683,121.5440],['绍兴',30.0303,120.5802],['温州',27.9949,120.6994],['舟山',29.9853,122.2072],['扬州',32.3942,119.4129],['无锡',31.4912,120.3119],['南宁',22.8170,108.3669],['桂林',25.2742,110.2991],['阳朔',24.7785,110.4966],['北海',21.4813,109.1202],['贵阳',26.6470,106.6302],['安顺',26.2531,105.9476],['张家界',29.1171,110.4792],['凤凰',27.9483,109.5985],['海口',20.0440,110.1999],['万宁',18.7953,110.3911],['汕头',23.3535,116.6822],['珠海',22.2710,113.5767],['兰州',36.0611,103.8343],['敦煌',40.1421,94.6619],['张掖',38.9259,100.4498],['西宁',36.6171,101.7782],['银川',38.4872,106.2309],['香港',22.3193,114.1694],['澳门',22.1987,113.5439],['台北',25.0330,121.5654],['台中',24.1477,120.6736],['高雄',22.6273,120.3014],['花莲',23.9872,121.6015],['九寨沟',33.2520,103.9186],['乐山',29.5521,103.7656],['稻城',29.0350,100.2980]];
cities.push(['常州',31.8107,119.9741]);
const suggestions=[cities[cities.length-1],...cities.slice(0,8)].map(([name,lat,lng])=>({id:'city-'+name,name,lat,lng,photos:[],date:'',note:''}));
let hiddenPlaceIds=new Set();
const emptySelection=()=>({id:'',name:'添加第一站',lat:32,lng:108,photos:[],date:'',note:''});
const markerNodes=new Map();let mapLabelsDirty=true;
let albums=[],selected={...suggestions[0]},db,globe,editMode=false,draftCoords=null,lightboxIndex=0,toastTimer,busy=false;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4500)}
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open('tongyou-private-planet',2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('albums'))r.result.createObjectStore('albums',{keyPath:'id'});if(!r.result.objectStoreNames.contains('settings'))r.result.createObjectStore('settings')};r.onblocked=()=>toast('请关闭旧版相册窗口，升级后会保留已有照片。');r.onsuccess=()=>{r.result.onversionchange=()=>r.result.close();resolve(r.result)};r.onerror=()=>reject(r.error)})}
function readAlbums(){return new Promise((resolve,reject)=>{const r=db.transaction('albums').objectStore('albums').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function readHiddenPlaces(){return new Promise((resolve,reject)=>{const r=db.transaction('settings').objectStore('settings').get('hiddenPlaces');r.onsuccess=()=>resolve(new Set(r.result||[]));r.onerror=()=>reject(r.error)})}
async function commit(records,remove=[],hide=[]){
 if(!db)throw new Error('浏览器暂时无法保存，请使用普通模式打开 Edge 或 Chrome。');
 const nextHidden=new Set([...hiddenPlaceIds,...hide]);records.forEach(p=>nextHidden.delete(p.id));
 await new Promise((resolve,reject)=>{const tx=db.transaction(['albums','settings'],'readwrite');const store=tx.objectStore('albums');records.forEach(p=>store.put(p));remove.forEach(id=>store.delete(id));tx.objectStore('settings').put([...nextHidden],'hiddenPlaces');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('保存中断'))});
 hiddenPlaceIds=nextHidden;albums=await readAlbums();renderAll()
}
function allPlaces(){return [...albums,...suggestions.filter(p=>!hiddenPlaceIds.has(p.id)&&!albums.some(a=>a.id===p.id||a.name===p.name))]}
const coordinates=p=>`${Math.abs(p.lat).toFixed(2)}° ${p.lat>=0?'N':'S'} / ${Math.abs(p.lng).toFixed(2)}° ${p.lng>=0?'E':'W'}`;
function selectPlace(place,move=true){selected=albums.find(p=>p.id===place.id)||allPlaces().find(p=>p.id===place.id)||{id:place.id,name:place.name,lat:place.lat,lng:place.lng,photos:[],date:'',note:''};renderAll();if(globe&&move){globe.controls().autoRotate=false;setRotateLabel(false);globe.pointOfView({lat:selected.lat,lng:selected.lng,altitude:1.55},1100)}}
function renderAll(){selected=albums.find(p=>p.id===selected.id)||selected;$('#placeCount').textContent=String(albums.length).padStart(2,'0');$('#photoCount').textContent=String(albums.reduce((n,p)=>n+p.photos.length,0)).padStart(2,'0');$('#placeName').textContent=selected.name;$('#placeSub').textContent=coordinates(selected);$('#placeTag').textContent=albums.some(p=>p.id===selected.id)?'属于我们的坐标':'下一段故事';$('#listHint').textContent=albums.length?'点亮的每一站，都值得再看一次':'选一个地方，开始收藏';$('#emptyMemory').hidden=selected.photos.length>0;$('#memoryInfo').hidden=!(selected.date||selected.note);$('#memoryDate').textContent=selected.date?selected.date.replaceAll('-',' / '):'';$('#memoryNote').textContent=selected.note||'';$('#uploadBtn').innerHTML=!selected.id?'<span>＋</span> 添加我们的第一站':selected.photos.length?'<span>＋</span> 继续收藏照片':'<span>＋</span> 添加我们的照片';renderBook();$('#deleteRegionBtn').hidden=!selected.id;const list=$('#places');list.replaceChildren();for(const p of allPlaces()){const b=document.createElement('button');b.className='place-chip'+(p.id===selected.id?' active':'');b.setAttribute('aria-pressed',p.id===selected.id?'true':'false');const pin=document.createElement('span');pin.className='pin';pin.textContent='⌖';const body=document.createElement('span'),name=document.createElement('strong'),meta=document.createElement('small');name.textContent=p.name;meta.textContent=p.photos.length?`${p.photos.length} 张回忆`:albums.some(a=>a.id===p.id)?'已收藏 · 待加照片':'待添加回忆';body.append(name,meta);b.append(pin,body);b.onclick=()=>selectPlace(p);list.append(b)}const add=document.createElement('button');add.className='place-chip add';add.textContent='＋ 添加足迹';add.onclick=()=>openEditor(false);list.append(add);updateGlobe()}
function openEditor(edit,coords=null){edit=edit&&!!selected.id;editMode=edit;draftCoords=coords;$('#cityInput').value=edit?selected.name:'';$('#dateInput').value=edit?selected.date:'';$('#noteInput').value=edit?selected.note:'';$('#deletePlace').hidden=!edit||!selected.id;$('#formError').textContent='';$('#locationTip').textContent=coords?`已选坐标 ${coordinates(coords)}，请填写景点或地点名称。`:'从城市建议中选择；也可关闭窗口，在中国地图上点击准确位置。';$('#placeDialog').showModal()}
$('#placeForm').onsubmit=async e=>{e.preventDefault();if(busy)return;const name=$('#cityInput').value.trim();const match=cities.find(c=>c[0]===name||c[0]+'市'===name);let coords=draftCoords||(match?{lat:match[1],lng:match[2]}:editMode?{lat:selected.lat,lng:selected.lng}:null);if(!name||!coords){$('#formError').textContent='请选择建议中的城市，或在中国地图上点击一个位置。';return}const same=albums.find(p=>(p.name===name||(!editMode&&!draftCoords&&match&&p.id==='city-'+match[0]))&&(!editMode||p.id!==selected.id));if(same){$('#formError').textContent='这个地点已经在相册中，请选择它继续添加回忆。';return}const next={...(editMode?selected:{id:match&&!draftCoords?'city-'+match[0]:crypto.randomUUID(),photos:[]}),...coords,name,date:$('#dateInput').value,note:$('#noteInput').value.trim()};try{await commit([next]);selectPlace(next);$('#placeDialog').close();toast('这段回忆，已经收藏好了')}catch(err){$('#formError').textContent=err.message||'保存失败，请导出备份后检查浏览器空间。'}};
$('#addBtn').onclick=()=>openEditor(false);$('#editBtn').onclick=()=>openEditor(true);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));cities.forEach(([name])=>{const o=document.createElement('option');o.value=name;$('#cityList').append(o)});
async function deleteSelectedRegion(){
 if(busy){toast('照片正在保存，请稍后再删除地区。');return}
 if(!selected.id)return;
 if(!confirm(selected.photos.length?`删除“${selected.name}”及其中 ${selected.photos.length} 张照片？电脑里的原始照片不会被删除。`:`从地图和地点列表移除“${selected.name}”？以后可以重新添加。`))return;
 try{const id=selected.id;await commit([],[id],[id]);selected=allPlaces()[0]||emptySelection();renderAll();if($('#placeDialog').open)$('#placeDialog').close();toast('这个地区及相册已移除，需要时可重新添加')}catch{toast('删除失败，请重试')}
}
$('#deletePlace').onclick=deleteSelectedRegion;$('#deleteRegionBtn').onclick=deleteSelectedRegion;
function loadImage(url){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('照片无法读取，请使用 JPG、PNG 或 WebP 图片。'));i.src=url})}
async function preparePhoto(file){if(!/^image\/(jpeg|png|webp|gif|avif)$/.test(file.type))throw new Error('请选择 JPG、PNG、WebP、GIF 或 AVIF 图片；HEIC 请先转成 JPG。');if(file.size>25*1024*1024)throw new Error('单张照片请控制在 25 MB 以内。');const url=URL.createObjectURL(file);try{const img=await loadImage(url);const scale=Math.min(1,2200/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);return {id:crypto.randomUUID(),name:file.name,data:canvas.toDataURL('image/jpeg',.88)}}finally{URL.revokeObjectURL(url)}}
$('#uploadBtn').onclick=()=>selected.id?$('#photoInput').click():openEditor(false);$('#photoInput').onchange=async e=>{const files=[...e.target.files];e.target.value='';if(!files.length||busy)return;if(files.length>50){toast('一次最多添加 50 张照片，可以分批添加。');return}const target=structuredClone(selected);busy=true;$('#uploadBtn').disabled=true;try{for(let i=0;i<files.length;i++){toast(`正在珍藏第 ${i+1} / ${files.length} 张照片…`);target.photos.push(await preparePhoto(files[i]))}await commit([target]);selectPlace(target,false);toast(`已收藏 ${files.length} 张回忆`);navigator.storage?.persist?.().catch(()=>{})}catch(err){toast(err.name==='QuotaExceededError'?'保存空间不足，请先导出相册备份。':err.message||'照片保存失败，请重试。')}finally{busy=false;$('#uploadBtn').disabled=false}};
function openPhoto(i){lightboxIndex=i;showPhoto();$('#lightbox').showModal()}
function showPhoto(){const p=selected.photos[lightboxIndex];if(!p){$('#lightbox').close();return}$('#largePhoto').src=p.data;$('#largePhoto').alt=p.name||selected.name+'旅行照片';$('#photoCaption').textContent=`${selected.name} · ${lightboxIndex+1} / ${selected.photos.length}`;$('#prevPhoto').hidden=$('#nextPhoto').hidden=selected.photos.length<2}
$('#prevPhoto').onclick=()=>{lightboxIndex=(lightboxIndex-1+selected.photos.length)%selected.photos.length;showPhoto()};$('#nextPhoto').onclick=()=>{lightboxIndex=(lightboxIndex+1)%selected.photos.length;showPhoto()};document.addEventListener('keydown',e=>{if(!$('#lightbox').open)return;if(e.key==='ArrowLeft')$('#prevPhoto').click();if(e.key==='ArrowRight')$('#nextPhoto').click()});$('#deletePhoto').onclick=async()=>{if(!confirm('删除这张照片？此操作不会删除电脑里的原始文件。'))return;const next=structuredClone(selected);next.photos.splice(lightboxIndex,1);try{await commit([next]);lightboxIndex=Math.min(lightboxIndex,selected.photos.length-1);showPhoto();toast('照片已从相册移除')}catch{toast('删除失败，请重试')}};
$('#backupBtn').onclick=()=>$('#backupDialog').showModal();$('#exportBtn').onclick=()=>{if(!albums.length){toast('先收藏一个地点，再导出相册吧');return}const blob=new Blob([JSON.stringify({format:'tongyou-planet',version:1,exportedAt:new Date().toISOString(),albums})],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`同游相册备份-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('备份已导出，请保存在安全的位置')};$('#importBtn').onclick=()=>$('#importInput').click();
function validateBackup(data){if(data?.format!=='tongyou-planet'||data.version!==1||!Array.isArray(data.albums)||data.albums.length>1000)throw new Error('这不是有效的同游相册备份。');const ids=new Set();return data.albums.map(p=>{if(!p||typeof p.id!=='string'||p.id.length>100||ids.has(p.id)||typeof p.name!=='string'||!p.name.trim()||p.name.length>40||!Number.isFinite(p.lat)||p.lat< -90||p.lat>90||!Number.isFinite(p.lng)||p.lng< -180||p.lng>180||!Array.isArray(p.photos)||p.photos.length>2000||typeof p.note!=='string'||p.note.length>600||typeof p.date!=='string'||(p.date&&!/^\d{4}-\d{2}-\d{2}$/.test(p.date)))throw new Error('备份中的地点资料不完整。');ids.add(p.id);return {id:p.id,name:p.name,lat:p.lat,lng:p.lng,note:p.note,date:p.date,photos:p.photos.map(f=>{if(!f||typeof f.id!=='string'||typeof f.name!=='string'||f.name.length>500||typeof f.data!=='string'||!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/]+=*$/.test(f.data)||f.data.length>15*1024*1024)throw new Error('备份中有无法识别的图片。');return {id:f.id,name:f.name,data:f.data}})}})}
$('#importInput').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f||busy)return;if(f.size>200*1024*1024){toast('这份备份超过 200 MB，暂时无法导入。');return}try{const records=validateBackup(JSON.parse(await f.text()));if(!records.length){toast('这份备份中还没有回忆。');return}const conflicts=records.filter(p=>albums.some(a=>a.id===p.id)).length;if(!confirm(`导入 ${records.length} 个地点的回忆？${conflicts?`其中 ${conflicts} 个已有地点会用备份内容替换。`:'现有回忆会保留。'}`))return;busy=true;await commit(records);selectPlace(records[0]);$('#backupDialog').close();toast('回忆已经回到这颗星球')}catch(err){toast(err instanceof SyntaxError?'备份文件损坏或格式不正确。':err.message||'导入失败，原有回忆已保留。')}finally{busy=false}};
function setRotateLabel(v){$('#rotateBtn').textContent=v?'Ⅱ':'⏵';$('#rotateBtn').setAttribute('aria-pressed',String(v));$('#rotateBtn').setAttribute('aria-label',v?'暂停自动旋转':'开启自动旋转')}
function allMapPlaces(){
 const places=allPlaces();return [...places,...cities.map(([name,lat,lng])=>({id:'city-'+name,name,lat,lng,photos:[],date:'',note:''})).filter(p=>!hiddenPlaceIds.has(p.id)&&!places.some(a=>a.id===p.id||a.name===p.name))];
}
function updateGlobe(){if(!globe)return;markerNodes.clear();globe.htmlElementsData(allMapPlaces().map(({id,name,lat,lng})=>({id,name,lat,lng}))).ringsData(albums.map(({id,lat,lng})=>({id,lat,lng})));mapLabelsDirty=true}
function makeCityMarker(p){
 const b=document.createElement('button'),saved=albums.some(a=>a.id===p.id);
 b.className='marker map-city'+(saved?' saved visited':' reference')+(p.id===selected.id?' active':'');b.title=p.name;b.setAttribute('aria-label','查看'+p.name+'相册');
 const label=document.createElement('span');label.className='marker-name';label.textContent=p.name;const link=document.createElement('i');link.className='marker-link';b.append(link,label);
 b.onclick=e=>{e.stopPropagation();selectPlace(p)};markerNodes.set(p.id,{p,b,saved});mapLabelsDirty=true;return b;
}
function layoutMapLabels(){
 if(!globe)return;const bounds=$('#globe').getBoundingClientRect(),camera=globe.camera(),occupied=[],items=[...markerNodes.values()];
 items.sort((a,b)=>(b.p.id===selected.id)-(a.p.id===selected.id)||Number(b.saved)-Number(a.saved));
 for(const {p,b,saved} of items){
  const w=globe.getCoords(p.lat,p.lng,.03),v=new THREE.Vector3(w.x,w.y,w.z),front=v.dot(camera.position)>v.lengthSq();
  const screen=globe.getScreenCoords(p.lat,p.lng,.03),width=Math.min(168,p.name.length*11+14),height=23;
  const offsets=saved||p.id===selected.id?[[10,-10],[10,12],[-width-5,-10],[-width-5,12],[8,-35],[-width-5,-35],[8,35]]:[[9,-10]];
  let chosen=null;
  if(front&&screen.x>8&&screen.x<bounds.width-8&&screen.y>8&&screen.y<bounds.height-8){
   for(const [dx,dy]of offsets){const rect={x:screen.x+dx,y:screen.y+dy,w:width,h:height};
    if(rect.x<4||rect.y<4||rect.x+rect.w>bounds.width-4||rect.y+rect.h>bounds.height-4)continue;
    if(occupied.some(r=>rect.x<r.x+r.w+4&&rect.x+rect.w+4>r.x&&rect.y<r.y+r.h+3&&rect.y+rect.h+3>r.y))continue;
    chosen={dx,dy,rect};break;
   }
  }
  b.classList.toggle('label-hidden',!chosen);b.classList.toggle('back-city',!front);
  if(chosen){occupied.push(chosen.rect);b.style.setProperty('--label-x',chosen.dx+'px');b.style.setProperty('--label-y',chosen.dy+'px');const endX=chosen.dx<0?chosen.dx+width:chosen.dx,endY=chosen.dy+height/2;const leader=b.querySelector('.marker-link');leader.style.width=Math.hypot(endX,endY)+'px';leader.style.transform=`rotate(${Math.atan2(endY,endX)}rad)`;leader.hidden=chosen.dy===-10;}
 }
 mapLabelsDirty=false;
}
function polygonsOf(f){return f.geometry.type==='MultiPolygon'?f.geometry.coordinates:[f.geometry.coordinates]}
function insideRing(lat,lng,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const [x,y]=ring[i],[xj,yj]=ring[j];if((y>lat)!==(yj>lat)&&lng<(xj-x)*(lat-y)/(yj-y)+x)inside=!inside}return inside}
function insideChina({lat,lng}){return MAP_DATA.china.features.some(f=>polygonsOf(f).some(p=>insideRing(lat,lng,p[0])&&!p.slice(1).some(r=>insideRing(lat,lng,r))))}
async function makeMapTexture(){const canvas=document.createElement('canvas');canvas.width=4096;canvas.height=2048;const ctx=canvas.getContext('2d');ctx.fillStyle='#081423';ctx.fillRect(0,0,4096,2048);const night=await loadImage(EARTH_TEXTURE);ctx.globalAlpha=.6;ctx.drawImage(night,0,0,4096,2048);ctx.globalAlpha=1;function shape(p){ctx.beginPath();for(const ring of p){ring.forEach(([lng,lat],i)=>{const x=(lng+180)/360*4096,y=(90-lat)/180*2048;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath()}}
 for(const f of MAP_DATA.world.features){if(f.properties.ADMIN==='Antarctica')continue;for(const p of polygonsOf(f)){shape(p);ctx.fillStyle='rgba(26,53,74,.55)';ctx.fill('evenodd');ctx.strokeStyle='#35546a';ctx.lineWidth=.7;ctx.stroke()}}
 ctx.save();for(const f of MAP_DATA.china.features){for(const p of polygonsOf(f)){shape(p);ctx.fillStyle='rgba(207,157,68,.66)';ctx.fill('evenodd');ctx.strokeStyle='#f4cc83';ctx.lineWidth=1.1;ctx.shadowColor='#f3b850';ctx.shadowBlur=5;ctx.stroke()}}ctx.restore();return canvas.toDataURL('image/png')}
async function initGlobe(){try{const texture=await makeMapTexture();const container=$('#globe');globe=new Globe(container,{animateIn:false,rendererConfig:{antialias:true,alpha:true}}).width(container.clientWidth).height(container.clientHeight).backgroundColor('#00000000').globeImageUrl(texture).atmosphereColor('#5abcec').atmosphereAltitude(.16).showGraticules(false).onGlobeClick(coords=>{if(!insideChina(coords)){toast('请选择中国境内的地点，或从下方添加城市。');return}globe.controls().autoRotate=false;setRotateLabel(false);openEditor(false,{lat:coords.lat,lng:coords.lng})}).htmlLat('lat').htmlLng('lng').htmlAltitude(.03).htmlElement(makeCityMarker).ringLat('lat').ringLng('lng').ringAltitude(.008).ringColor(()=>t=>`rgba(127,221,255,${1-t})`).ringMaxRadius(2.7).ringPropagationSpeed(1.4).ringRepeatPeriod(1600);
 const material=globe.globeMaterial();material.color.set('#b2c5d9');material.emissive.set('#101a25');material.emissiveIntensity=.45;material.shininess=8;
 globe.pointOfView({lat:32,lng:108,altitude:2.2},0);const controls=globe.controls();controls.enablePan=false;controls.minDistance=135;controls.maxDistance=600;controls.autoRotate=false;controls.autoRotateSpeed=.28;controls.enableDamping=true;controls.dampingFactor=.08;
 const paths=[];for(const f of MAP_DATA.world.features){if(['China','Taiwan'].includes(f.properties.ADMIN))continue;const polygons=f.geometry.type==='MultiPolygon'?f.geometry.coordinates:[f.geometry.coordinates];for(const polygon of polygons)paths.push(polygon[0].map(([lng,lat])=>({lat,lng})))}globe.pathsData(paths).pathPoints(p=>p).pathPointLat('lat').pathPointLng('lng').pathPointAlt(.001).pathColor(()=> '#36526a').pathStroke(.18).pathTransitionDuration(0);
 const scene=globe.scene();const orbitGroup=new THREE.Group();for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(129+i*3,.11+(i===0?.09:0),6,256),new THREE.MeshBasicMaterial({color:i===1?0x6cbbd9:0x4d809e,transparent:true,opacity:i===0?.48:.2,depthWrite:false}));ring.rotation.x=Math.PI/2;orbitGroup.add(ring)}orbitGroup.rotation.z=-.3;orbitGroup.rotation.x=.25;scene.add(orbitGroup);
 globe.lights([new THREE.AmbientLight('#8a9bb9',.42)]);
 globe.bumpImageUrl(PLANET_TEXTURES.earthBump);globe.globeMaterial().bumpScale=.42;
 await installCosmos(globe);
 const previousFrame=scene.onBeforeRender;scene.onBeforeRender=function(...args){previousFrame.apply(this,args);if(mapLabelsDirty)layoutMapLabels()};
 const resize=new ResizeObserver(()=>{globe.width(container.clientWidth).height(container.clientHeight);mapLabelsDirty=true});resize.observe(container);controls.addEventListener('change',()=>{mapLabelsDirty=true;$('#coordinates').textContent=coordinates(globe.pointOfView())});controls.addEventListener('start',()=>{controls.autoRotate=false;setRotateLabel(false)});$('#homeBtn').onclick=()=>{controls.autoRotate=false;setRotateLabel(false);globe.pointOfView({lat:32,lng:108,altitude:2.2},1000)};$('#zoomIn').onclick=()=>{const p=globe.pointOfView();globe.pointOfView({...p,altitude:Math.max(.4,p.altitude*.78)},400)};$('#zoomOut').onclick=()=>{const p=globe.pointOfView();globe.pointOfView({...p,altitude:Math.min(4.8,p.altitude*1.25)},400)};$('#rotateBtn').onclick=()=>{controls.autoRotate=!controls.autoRotate;setRotateLabel(controls.autoRotate)};$('#loading').hidden=true;updateGlobe();window.__planetReady=true;syncSceneActivity();
 }catch(err){window.__globeFailed=true;console.error(err);$('#loading').classList.add('globe-error');$('#loading').textContent='地球暂时无法显示。请使用新版 Edge 或 Chrome，并开启浏览器图形加速。你仍可在下方选择地点管理相册。'}}
async function start(){
 renderAll();
 try{db=await openDb();albums=await readAlbums();hiddenPlaceIds=await readHiddenPlaces();selected=allPlaces()[0]||emptySelection();renderAll()}catch{toast('浏览器无法保存照片，请使用普通窗口打开 Edge 或 Chrome。')}
 initGlobe();
 if(document.modelContext?.registerTool){try{document.modelContext.registerTool({
  name:'list_travel_memories',description:'查看旅行相册的地点与照片数量，不返回私人照片内容。',
  inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},
  execute:()=>({places:albums.map(({id,name,date,photos})=>({id,name,date,photoCount:photos.length}))})
 })}catch{}}
}
let lightboxTouch=null,lastPhotoWheel=0;
$('#lightbox figure').addEventListener('touchstart',e=>{if(e.touches.length===1)lightboxTouch={x:e.touches[0].clientX,y:e.touches[0].clientY}},{passive:true});
$('#lightbox figure').addEventListener('touchend',e=>{if(!lightboxTouch)return;const dx=e.changedTouches[0].clientX-lightboxTouch.x,dy=e.changedTouches[0].clientY-lightboxTouch.y;lightboxTouch=null;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)&&selected.photos.length>1)(dx<0?$('#nextPhoto'):$('#prevPhoto')).click()},{passive:true});
$('#lightbox figure').addEventListener('touchcancel',()=>{lightboxTouch=null},{passive:true});
$('#lightbox figure').addEventListener('wheel',e=>{if(e.ctrlKey||selected.photos.length<2)return;e.preventDefault();const now=Date.now(),delta=Math.abs(e.deltaX)>Math.abs(e.deltaY)?e.deltaX:e.deltaY;if(Math.abs(delta)>8&&now-lastPhotoWheel>350){lastPhotoWheel=now;(delta>0?$('#nextPhoto'):$('#prevPhoto')).click()}},{passive:false});

